In [1]:
import pandas as pd
import os
import sqlite3
from sqlalchemy import create_engine
import mysql.connector

In [2]:
create = create_engine("sqlite:/// election.db")

In [3]:
def ingest_db(file_path, table_name, conn):
    df1 = pd.read_csv(file_path)
    df1.to_sql(table_name, con=conn, if_exists="replace", index=False)
    print("Ingested:", table_name, df1.shape)   # moved inside function & fixed df name

conn = sqlite3.connect("election.db")

file_path = "C:/Users/amanp/Downloads/election commision.csv"
table_name = os.path.splitext(os.path.basename(file_path))[0]  

ingest_db(file_path, table_name, conn)

Ingested: election commision (61725, 12)

In [4]:
tables= pd.read_sql_query("select name from sqlite_master where type ='table'",conn)
print(tables)

                 name
0            election
1        final_result
2           elections
3       final_results
4  election commision

In [5]:
for table in tables["name"]:
    print(pd.read_sql_query(f'SELECT count(*) AS rows FROM "{table}"', conn))
    print(pd.read_sql_query(f'SELECT * FROM "{table}" LIMIT 5', conn))

    rows
0  61725
    State/Ut Name  Parliamentryconstituencies ParliamentryNumber  \
0  Andhra Pradesh                           1              Araku
1  Andhra Pradesh                           1              Araku
2  Andhra Pradesh                           1              Araku
3  Andhra Pradesh                           1              Araku
4  Andhra Pradesh                           1              Araku

   Total Electors In PC  Assemblyconstituencies AssemblyName  \
0               1557153                      10    Palakonda
1               1557153                      10    Palakonda
2               1557153                      10    Palakonda
3               1557153                      10    Palakonda
4               1557153                      10    Palakonda

   Total Electors In AC  Total Valid Votes In State  Nota Votes Evm In AC  \
0                195673                    33327256                  4441
1                195673                    33327256                  4441
2                195673                    33327256                  4441
3                195673                    33327256                  4441
4                195673                    33327256                  4441

            Candidate Name   Party  Votes Secured Evm
0  APPALANARASA PACHIPENTA  CPI(M)               3873
1   AVASHYA LAHARI . VARAM     BSP               1155
2        KOTHAPALLI GEETHA     BJP              66695
3       GUMMA THANUJA RANI   YSRCP              63302
4          CHANTI BADNAINA    JBNP               1977
   rows
0     0
Empty DataFrame
Columns: [State_Ut_Name, Parliamentryconstituencies, ParliamentryName, Total_Electors_In_PC, Assemblyconstituencies, AssemblyName, Total_Electors_In_AC, Total_Valid_Votes_In_State, Nota_Votes_Evm_In_AC, Candidate_Name, Party, Votes_Secured_Evm, Total_Votes, Turnout_generalpercent, Votesharepercentage, Votes_pc_party, Winning_Party, Margin]
Index: []
    rows
0  61725
    State/Ut Name  Parliamentryconstituencies ParliamentryName  \
0  Andhra Pradesh                           1            Araku
1  Andhra Pradesh                           1            Araku
2  Andhra Pradesh                           1            Araku
3  Andhra Pradesh                           1            Araku
4  Andhra Pradesh                           1            Araku

   Total Electors In PC  Assemblyconstituencies AssemblyName  \
0               1557153                      10    Palakonda
1               1557153                      10    Palakonda
2               1557153                      10    Palakonda
3               1557153                      10    Palakonda
4               1557153                      10    Palakonda

   Total Electors In AC  Total Valid Votes In State  Nota Votes Evm In AC  \
0                195673                    33327256                  4441
1                195673                    33327256                  4441
2                195673                    33327256                  4441
3                195673                    33327256                  4441
4                195673                    33327256                  4441

            Candidate Name   Party  Votes Secured Evm
0  APPALANARASA PACHIPENTA  CPI(M)               3873
1   AVASHYA LAHARI . VARAM     BSP               1155
2        KOTHAPALLI GEETHA     BJP              66695
3       GUMMA THANUJA RANI   YSRCP              63302
4          CHANTI BADNAINA    JBNP               1977
    rows
0  61725
  State/Ut Name  Parliamentryconstituencies ParliamentryName  \
0     Rajasthan                          13            AJMER
1     Rajasthan                          13            AJMER
2     Rajasthan                          13            AJMER
3     Rajasthan                          13            AJMER
4     Rajasthan                          13            AJMER

   Total Electors In PC  Assemblyconstituencies AssemblyName  \
0               1999399                      98   KISHANGARH
1               1999399                     105        KEKRI
2               1999399                     104       MASUDA
3               1999399                      99      PUSHKAR
4               1999399                     102    NASIRABAD

   Total Electors In AC  Total Valid Votes In State  Nota Votes Evm In AC  \
0                286257                    32885413                  1816
1                264896                    32885413                  1742
2                275740                    32885413                  1436
3                254914                    32885413                  1496
4                235530                    32885413                  1225

        Candidate Name Party  Votes Secured Evm  Total_Votes  \
0  BHAGIRATH CHOUDHARY   BJP             107716      1180237
1  BHAGIRATH CHOUDHARY   BJP              98471      1180237
2  BHAGIRATH CHOUDHARY   BJP              97421      1180237
3  BHAGIRATH CHOUDHARY   BJP              95780      1180237
4  BHAGIRATH CHOUDHARY   BJP              89146      1180237

   Turnout generalpercent  Votesharepercentage  Votes_pc_party Winning Party  \
0               59.029588             9.126642          741151           BJP
1               59.029588             8.343324          741151           BJP
2               59.029588             8.254359          741151           BJP
3               59.029588             8.115319          741151           BJP
4               59.029588             7.553229          741151           BJP

   Margin
0    9245
1    9245
2    9245
3    9245
4    9245
    rows
0  61725
    State/Ut Name  Pc No PC Name  Total Electors In PC  AC No    AC Name  \
0  Andhra Pradesh      1   Araku               1557153     10  Palakonda
1  Andhra Pradesh      1   Araku               1557153     10  Palakonda
2  Andhra Pradesh      1   Araku               1557153     10  Palakonda
3  Andhra Pradesh      1   Araku               1557153     10  Palakonda
4  Andhra Pradesh      1   Araku               1557153     10  Palakonda

   Total Electors In AC  Total Valid Votes In State  Nota Votes Evm In AC  \
0                195673                    33327256                  4441
1                195673                    33327256                  4441
2                195673                    33327256                  4441
3                195673                    33327256                  4441
4                195673                    33327256                  4441

            Candidate Name   Party  Votes Secured Evm
0  APPALANARASA PACHIPENTA  CPI(M)               3873
1   AVASHYA LAHARI . VARAM     BSP               1155
2        KOTHAPALLI GEETHA     BJP              66695
3       GUMMA THANUJA RANI   YSRCP              63302
4          CHANTI BADNAINA    JBNP               1977

In [6]:
ad = pd.read_sql_query('SELECT * FROM "election commision"', conn)
print(ad.head())

    State/Ut Name  Pc No PC Name  Total Electors In PC  AC No    AC Name  \
0  Andhra Pradesh      1   Araku               1557153     10  Palakonda
1  Andhra Pradesh      1   Araku               1557153     10  Palakonda
2  Andhra Pradesh      1   Araku               1557153     10  Palakonda
3  Andhra Pradesh      1   Araku               1557153     10  Palakonda
4  Andhra Pradesh      1   Araku               1557153     10  Palakonda

   Total Electors In AC  Total Valid Votes In State  Nota Votes Evm In AC  \
0                195673                    33327256                  4441
1                195673                    33327256                  4441
2                195673                    33327256                  4441
3                195673                    33327256                  4441
4                195673                    33327256                  4441

            Candidate Name   Party  Votes Secured Evm
0  APPALANARASA PACHIPENTA  CPI(M)               3873
1   AVASHYA LAHARI . VARAM     BSP               1155
2        KOTHAPALLI GEETHA     BJP              66695
3       GUMMA THANUJA RANI   YSRCP              63302
4          CHANTI BADNAINA    JBNP               1977

In [7]:
ad.columns.tolist()

['State/Ut Name',
 'Pc No',
 'PC Name',
 'Total Electors In PC',
 'AC No',
 'AC Name',
 'Total Electors In AC',
 'Total Valid Votes In State',
 'Nota Votes Evm In AC',
 'Candidate Name',
 'Party',
 'Votes Secured Evm']

In [8]:
ad["State/Ut Name"]

0        Andhra Pradesh
1        Andhra Pradesh
2        Andhra Pradesh
3        Andhra Pradesh
4        Andhra Pradesh
              ...
61720            Ladakh
61721            Ladakh
61722            Ladakh
61723            Ladakh
61724            Ladakh
Name: State/Ut Name, Length: 61725, dtype: object

In [9]:
ad

,State/Ut Name,Pc No,PC Name,Total Electors In PC,AC No,AC Name,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm
0,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,APPALANARASA PACHIPENTA,CPI(M),3873
1,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,AVASHYA LAHARI . VARAM,BSP,1155
2,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,KOTHAPALLI GEETHA,BJP,66695
3,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,GUMMA THANUJA RANI,YSRCP,63302
4,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,CHANTI BADNAINA,JBNP,1977
...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,TSERING NAMGYAL,INC,32014
61721,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,MOHMAD HANEEFA,IND,5733
61722,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TASHI GYALSON,BJP,10012
61723,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TSERING NAMGYAL,INC,3756
61724,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,MOHMAD HANEEFA,IND,58710

In [10]:
ad= ad.rename(columns = {"Pc No" : "Parliamentryconstituencies",
                            "AC No" : "Assemblyconstituencies", 
                            "PC Name" : "ParliamentryName",
                           "AC Name" : "AssemblyName"})
ad

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm
0,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,APPALANARASA PACHIPENTA,CPI(M),3873
1,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,AVASHYA LAHARI . VARAM,BSP,1155
2,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,KOTHAPALLI GEETHA,BJP,66695
3,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,GUMMA THANUJA RANI,YSRCP,63302
4,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,CHANTI BADNAINA,JBNP,1977
...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,TSERING NAMGYAL,INC,32014
61721,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,MOHMAD HANEEFA,IND,5733
61722,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TASHI GYALSON,BJP,10012
61723,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TSERING NAMGYAL,INC,3756
61724,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,MOHMAD HANEEFA,IND,58710

In [11]:
ad.columns.tolist()

['State/Ut Name',
 'Parliamentryconstituencies',
 'ParliamentryName',
 'Total Electors In PC',
 'Assemblyconstituencies',
 'AssemblyName',
 'Total Electors In AC',
 'Total Valid Votes In State',
 'Nota Votes Evm In AC',
 'Candidate Name',
 'Party',
 'Votes Secured Evm']

In [12]:
ad["State/Ut Name"].unique().tolist()

['Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'West Bengal',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Telangana',
 'Andaman & Nicobar Islands',
 'Chandigarh',
 'Dadra & Nagar Haveli and Daman & Diu',
 'NCT OF Delhi',
 'Lakshadweep',
 'Puducherry',
 'Jammu and Kashmir',
 'Ladakh']

In [13]:
pd.read_sql_query('select * from "election commision"',conn)

,State/Ut Name,Pc No,PC Name,Total Electors In PC,AC No,AC Name,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm
0,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,APPALANARASA PACHIPENTA,CPI(M),3873
1,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,AVASHYA LAHARI . VARAM,BSP,1155
2,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,KOTHAPALLI GEETHA,BJP,66695
3,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,GUMMA THANUJA RANI,YSRCP,63302
4,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,CHANTI BADNAINA,JBNP,1977
...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,TSERING NAMGYAL,INC,32014
61721,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,MOHMAD HANEEFA,IND,5733
61722,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TASHI GYALSON,BJP,10012
61723,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TSERING NAMGYAL,INC,3756
61724,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,MOHMAD HANEEFA,IND,58710

In [14]:
conn.execute('''alter table "election commision"
                 rename to "elections";''')

OperationalError: there is already another table or index with this name: elections

In [15]:
ad1 = pd.read_sql_query(""" select *
                            from elections """, conn)
ad1

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm
0,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,APPALANARASA PACHIPENTA,CPI(M),3873
1,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,AVASHYA LAHARI . VARAM,BSP,1155
2,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,KOTHAPALLI GEETHA,BJP,66695
3,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,GUMMA THANUJA RANI,YSRCP,63302
4,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,CHANTI BADNAINA,JBNP,1977
...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,TSERING NAMGYAL,INC,32014
61721,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,MOHMAD HANEEFA,IND,5733
61722,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TASHI GYALSON,BJP,10012
61723,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TSERING NAMGYAL,INC,3756
61724,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,MOHMAD HANEEFA,IND,58710

In [16]:
ad1 = pd.read_sql_query(""" select distinct ParliamentryName
                            from elections """, conn)
ad1

     ParliamentryName
0               Araku
1          Srikakulam
2        Vizianagaram
3       Visakhapatnam
4          Anakapalle
..                ...
535          SRINAGAR
536  ANANTNAG-RAJOURI
537          UDHAMPUR
538             JAMMU
539            Ladakh

[540 rows x 1 columns]

In [17]:
pd.read_sql_query(""" select *
                            from elections 
                            where ParliamentryName = 'Nawada'
                            and AssemblyName in ('Nawada','Hisua') """, conn)

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm
0,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,RANJIT KUMAR,BSP,3135
1,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,VIVEK THAKUR,BJP,82966
2,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,SHRAWAN KUMAR,RJD,63881
3,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,ANAND KUMAR VERMA,BJNJGD,1411
4,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,GANAURI PANDIT,PPID,782
5,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,GAUTAM KUMAR BABLOO,BGDRPP,1140
6,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,GUNJAN KUMAR,IND,5820
7,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,BINOD YADAV,IND,8274
8,Bihar,39,Nawada,2010286,237,Nawada,365188,42549333,1661,RANJIT KUMAR,BSP,2218
9,Bihar,39,Nawada,2010286,237,Nawada,365188,42549333,1661,VIVEK THAKUR,BJP,69763
10,Bihar,39,Nawada,2010286,237,Nawada,365188,42549333,1661,SHRAWAN KUMAR,RJD,67369
11,Bihar,39,Nawada,2010286,237,Nawada,365188,42549333,1661,ANAND KUMAR VERMA,BJNJGD,1021
12,Bihar,39,Nawada,2010286,237,Nawada,365188,42549333,1661,GANAURI PANDIT,PPID,650
13,Bihar,39,Nawada,2010286,237,Nawada,365188,42549333,1661,GAUTAM KUMAR BABLOO,BGDRPP,841
14,Bihar,39,Nawada,2010286,237,Nawada,365188,42549333,1661,GUNJAN KUMAR,IND,3271
15,Bihar,39,Nawada,2010286,237,Nawada,365188,42549333,1661,BINOD YADAV,IND,9661

In [18]:
ad

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm
0,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,APPALANARASA PACHIPENTA,CPI(M),3873
1,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,AVASHYA LAHARI . VARAM,BSP,1155
2,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,KOTHAPALLI GEETHA,BJP,66695
3,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,GUMMA THANUJA RANI,YSRCP,63302
4,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,CHANTI BADNAINA,JBNP,1977
...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,TSERING NAMGYAL,INC,32014
61721,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,MOHMAD HANEEFA,IND,5733
61722,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TASHI GYALSON,BJP,10012
61723,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TSERING NAMGYAL,INC,3756
61724,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,MOHMAD HANEEFA,IND,58710

In [19]:
ad[(ad["ParliamentryName"] == "Nawada") & (ad["AssemblyName"] == "Hisua")]

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm
7824,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,RANJIT KUMAR,BSP,3135
7825,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,VIVEK THAKUR,BJP,82966
7826,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,SHRAWAN KUMAR,RJD,63881
7827,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,ANAND KUMAR VERMA,BJNJGD,1411
7828,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,GANAURI PANDIT,PPID,782
7829,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,GAUTAM KUMAR BABLOO,BGDRPP,1140
7830,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,GUNJAN KUMAR,IND,5820
7831,Bihar,39,Nawada,2010286,236,Hisua,387202,42549333,2324,BINOD YADAV,IND,8274

# Total vote percentage in Parliamentry constituencies Name

In [20]:
votes_sum = ad.groupby("ParliamentryName")[["Votes Secured Evm"]].sum()
nota = ad.groupby("ParliamentryName")[["Nota Votes Evm In AC"]].first()

total_df = votes_sum.merge(nota, on="ParliamentryName")

total_df["Total_Votes"] = total_df["Votes Secured Evm"] + total_df["Nota Votes Evm In AC"]

ad = ad.merge(total_df[["Total_Votes"]], left_on="ParliamentryName", right_index=True, how="left")
ad

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm,Total_Votes
0,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,APPALANARASA PACHIPENTA,CPI(M),3873,1097249
1,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,AVASHYA LAHARI . VARAM,BSP,1155,1097249
2,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,KOTHAPALLI GEETHA,BJP,66695,1097249
3,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,GUMMA THANUJA RANI,YSRCP,63302,1097249
4,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,CHANTI BADNAINA,JBNP,1977,1097249
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,TSERING NAMGYAL,INC,32014,132056
61721,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,MOHMAD HANEEFA,IND,5733,132056
61722,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TASHI GYALSON,BJP,10012,132056
61723,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TSERING NAMGYAL,INC,3756,132056
61724,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,MOHMAD HANEEFA,IND,58710,132056

In [21]:
ad.rename(columns = {"Total_Votes_y":"Total_votes"}, inplace =True)
ad

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm,Total_Votes
0,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,APPALANARASA PACHIPENTA,CPI(M),3873,1097249
1,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,AVASHYA LAHARI . VARAM,BSP,1155,1097249
2,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,KOTHAPALLI GEETHA,BJP,66695,1097249
3,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,GUMMA THANUJA RANI,YSRCP,63302,1097249
4,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,CHANTI BADNAINA,JBNP,1977,1097249
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,TSERING NAMGYAL,INC,32014,132056
61721,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,MOHMAD HANEEFA,IND,5733,132056
61722,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TASHI GYALSON,BJP,10012,132056
61723,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TSERING NAMGYAL,INC,3756,132056
61724,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,MOHMAD HANEEFA,IND,58710,132056

**Now we find turnout percentage in general constituencies:**

**Turnout generalpercent in constituencies** = ( Total_votesTotal Electors in PC)*100

**Total Votes** = the sum of all votes cast in a Parliamentary Constituency (including all candidates and NOTA).

**Total Electors in PC** = the total number of registered voters in that constituency.

This gives the overall voter turnout percentage for each constituency. It represents the proportion of eligible voters who actually participated in the election

In [22]:
ad["Turnout generalpercent"] = (ad["Total_Votes"]/ad["Total Electors In PC"])*100

In [23]:
ad

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm,Total_Votes,Turnout generalpercent
0,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,APPALANARASA PACHIPENTA,CPI(M),3873,1097249,70.465073
1,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,AVASHYA LAHARI . VARAM,BSP,1155,1097249,70.465073
2,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,KOTHAPALLI GEETHA,BJP,66695,1097249,70.465073
3,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,GUMMA THANUJA RANI,YSRCP,63302,1097249,70.465073
4,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,CHANTI BADNAINA,JBNP,1977,1097249,70.465073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,TSERING NAMGYAL,INC,32014,132056,69.293090
61721,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,MOHMAD HANEEFA,IND,5733,132056,69.293090
61722,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TASHI GYALSON,BJP,10012,132056,69.293090
61723,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TSERING NAMGYAL,INC,3756,132056,69.293090
61724,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,MOHMAD HANEEFA,IND,58710,132056,69.293090

# Vote Percentage by each party or Party Performance Analysis

In [25]:
ad["Votesharepercentage"] = (ad["Votes Secured Evm"]/ad["Total_Votes"])*100
ad

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm,Total_Votes,Turnout generalpercent,Votesharepercentage
0,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,APPALANARASA PACHIPENTA,CPI(M),3873,1097249,70.465073,0.352974
1,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,AVASHYA LAHARI . VARAM,BSP,1155,1097249,70.465073,0.105263
2,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,KOTHAPALLI GEETHA,BJP,66695,1097249,70.465073,6.078383
3,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,GUMMA THANUJA RANI,YSRCP,63302,1097249,70.465073,5.769155
4,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,CHANTI BADNAINA,JBNP,1977,1097249,70.465073,0.180178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,TSERING NAMGYAL,INC,32014,132056,69.293090,24.242746
61721,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,MOHMAD HANEEFA,IND,5733,132056,69.293090,4.341340
61722,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TASHI GYALSON,BJP,10012,132056,69.293090,7.581632
61723,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TSERING NAMGYAL,INC,3756,132056,69.293090,2.844248
61724,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,MOHMAD HANEEFA,IND,58710,132056,69.293090,44.458412

## The column Votesharepercentage is calculated as:

**Votesharepercentage** = (Votes Secured EVM / Total_Votes)*100

**Votes Secured EVM**= the number of votes a candidate or party received through Electronic Voting Machines.

**Total_Votes** = the total number of registered voters in that Parliamentary Constituency (PC).

This gives the percentage of the total electorate that actually voted for a candidate/party, not just out of the people who cast their votes, but out of the entire eligible voting population.

# Total votes by party in that Parliamentry constituencies

In [26]:
ad["Votes_pc_party"] = ad.groupby(["ParliamentryName", "Party"])["Votes Secured Evm"].transform("sum")
ad

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm,Total_Votes,Turnout generalpercent,Votesharepercentage,Votes_pc_party
0,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,APPALANARASA PACHIPENTA,CPI(M),3873,1097249,70.465073,0.352974,119016
1,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,AVASHYA LAHARI . VARAM,BSP,1155,1097249,70.465073,0.105263,24858
2,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,KOTHAPALLI GEETHA,BJP,66695,1097249,70.465073,6.078383,417113
3,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,GUMMA THANUJA RANI,YSRCP,63302,1097249,70.465073,5.769155,471470
4,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,CHANTI BADNAINA,JBNP,1977,1097249,70.465073,0.180178,7205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,TSERING NAMGYAL,INC,32014,132056,69.293090,24.242746,35770
61721,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,MOHMAD HANEEFA,IND,5733,132056,69.293090,4.341340,64443
61722,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TASHI GYALSON,BJP,10012,132056,69.293090,7.581632,31505
61723,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TSERING NAMGYAL,INC,3756,132056,69.293090,2.844248,35770
61724,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,MOHMAD HANEEFA,IND,58710,132056,69.293090,44.458412,64443

### NOTA votes per constituency

In [27]:
ad["NOTA_percent"] = (ad["Nota Votes Evm In AC"] / ad["Total_Votes"]) * 100

# Winning party in that Particular constiuencies

In [28]:
winner = ad.groupby("ParliamentryName")["Votes Secured Evm"].idxmax()
winner
winner = ad.loc[winner, ["ParliamentryName", "Party"]].rename(columns={"Party": "Winning Party"})

ad = ad.merge(winner, on="ParliamentryName", how="left")
ad

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm,Total_Votes,Turnout generalpercent,Votesharepercentage,Votes_pc_party,NOTA_percent,Winning Party
0,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,APPALANARASA PACHIPENTA,CPI(M),3873,1097249,70.465073,0.352974,119016,0.404739,YSRCP
1,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,AVASHYA LAHARI . VARAM,BSP,1155,1097249,70.465073,0.105263,24858,0.404739,YSRCP
2,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,KOTHAPALLI GEETHA,BJP,66695,1097249,70.465073,6.078383,417113,0.404739,YSRCP
3,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,GUMMA THANUJA RANI,YSRCP,63302,1097249,70.465073,5.769155,471470,0.404739,YSRCP
4,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,CHANTI BADNAINA,JBNP,1977,1097249,70.465073,0.180178,7205,0.404739,YSRCP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,TSERING NAMGYAL,INC,32014,132056,69.293090,24.242746,35770,0.255952,IND
61721,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,MOHMAD HANEEFA,IND,5733,132056,69.293090,4.341340,64443,0.255952,IND
61722,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TASHI GYALSON,BJP,10012,132056,69.293090,7.581632,31505,0.422548,IND
61723,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TSERING NAMGYAL,INC,3756,132056,69.293090,2.844248,35770,0.422548,IND
61724,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,MOHMAD HANEEFA,IND,58710,132056,69.293090,44.458412,64443,0.422548,IND

In [29]:
ad.dtypes

State/Ut Name                  object
Parliamentryconstituencies      int64
ParliamentryName               object
Total Electors In PC            int64
Assemblyconstituencies          int64
AssemblyName                   object
Total Electors In AC            int64
Total Valid Votes In State      int64
Nota Votes Evm In AC            int64
Candidate Name                 object
Party                          object
Votes Secured Evm               int64
Total_Votes                     int64
Turnout generalpercent        float64
Votesharepercentage           float64
Votes_pc_party                  int64
NOTA_percent                  float64
Winning Party                  object
dtype: object

### Total seats won by party

In [30]:
ad= ad.sort_values(["ParliamentryName", "Votes Secured Evm"], ascending=[True, False])
winners_per_party = (
    ad.drop_duplicates(subset=["ParliamentryName"])["Winning Party"].value_counts()
)
print(winners_per_party)

Winning Party
BJP           247
INC            97
SP             37
AITC           28
DMK            20
TDP            16
JD(U)          12
SHS             8
NCPSP           7
SHSUBT          7
IND             7
LJPRV           5
AAAP            3
ADMK            3
CPI(M)          3
RJD             3
CPI             3
IUML            3
YSRCP           3
JMM             2
CPI(ML)(L)      2
JKN             2
JnP             2
JD(S)           2
NCP             1
SKM             1
MDMK            1
ASPKR           1
RLTP            1
ADAL            1
VOTPP           1
HAMS            1
KEC             1
RSP             1
UPPL            1
BJD             1
AIMIM           1
VCK             1
SAD             1
RLD             1
BHRTADVSIP      1
DMDK            1
Name: count, dtype: int64

# Marginal Victory

***Marginal victor*** = max(Votes Secured Evm) - 2ndmax(Votes Secured Evm)

In [31]:
df_sorted = ad.sort_values(["ParliamentryName", "Votes Secured Evm"], ascending=[True, False])
top2 = df_sorted.groupby("ParliamentryName").head()
margins = (
    top2.groupby("ParliamentryName")
        .apply(lambda x: x.iloc[0]["Votes Secured Evm"] - x.iloc[1]["Votes Secured Evm"])
        .reset_index(name="Margin")
)

ad = ad.merge(margins, on="ParliamentryName", how="left")
ad

C:\Users\amanp\AppData\Local\Temp\ipykernel_21588\2433604498.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.iloc[0]["Votes Secured Evm"] - x.iloc[1]["Votes Secured Evm"])

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm,Total_Votes,Turnout generalpercent,Votesharepercentage,Votes_pc_party,NOTA_percent,Winning Party,Margin
0,Rajasthan,13,AJMER,1999399,98,KISHANGARH,286257,32885413,1816,BHAGIRATH CHOUDHARY,BJP,107716,1180237,59.029588,9.126642,741151,0.153867,BJP,9245
1,Rajasthan,13,AJMER,1999399,105,KEKRI,264896,32885413,1742,BHAGIRATH CHOUDHARY,BJP,98471,1180237,59.029588,8.343324,741151,0.147597,BJP,9245
2,Rajasthan,13,AJMER,1999399,104,MASUDA,275740,32885413,1436,BHAGIRATH CHOUDHARY,BJP,97421,1180237,59.029588,8.254359,741151,0.121670,BJP,9245
3,Rajasthan,13,AJMER,1999399,99,PUSHKAR,254914,32885413,1496,BHAGIRATH CHOUDHARY,BJP,95780,1180237,59.029588,8.115319,741151,0.126754,BJP,9245
4,Rajasthan,13,AJMER,1999399,102,NASIRABAD,235530,32885413,1225,BHAGIRATH CHOUDHARY,BJP,89146,1180237,59.029588,7.553229,741151,0.103793,BJP,9245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Telangana,5,Zahirabad,1642425,16,Kamareddy,255175,21904129,527,ROMALA BABU DURGAIAH,IPBP,88,1222431,74.428421,0.007199,601,0.043111,INC,17519
61721,Telangana,5,Zahirabad,1642425,35,Narayankhed,237309,21904129,396,ROMALA BABU DURGAIAH,IPBP,80,1222431,74.428421,0.006544,601,0.032394,INC,17519
61722,Telangana,5,Zahirabad,1642425,38,Zaheerabad,275667,21904129,351,ROMALA BABU DURGAIAH,IPBP,74,1222431,74.428421,0.006054,601,0.028713,INC,17519
61723,Telangana,5,Zahirabad,1642425,14,Banswada,197025,21904129,365,ASHOK TALARI,IND,73,1222431,74.428421,0.005972,30999,0.029859,INC,17519
61724,Telangana,5,Zahirabad,1642425,14,Banswada,197025,21904129,365,ROMALA BABU DURGAIAH,IPBP,61,1222431,74.428421,0.004990,601,0.029859,INC,17519

In [32]:
df_sorted = ad
df_sorted = df_sorted.drop_duplicates(subset=["ParliamentryName", "Candidate Name"])

top2 = df_sorted.groupby("ParliamentryName").head(2)
result = (
    top2.groupby("ParliamentryName")
        .apply(lambda x: pd.Series({
            "Winner": x.iloc[0]["Candidate Name"],
            "Winning Party": x.iloc[0]["Party"],
            "Winner Votes": x.iloc[0]["Votes Secured Evm"],
            "Runner-up": x.iloc[1]["Candidate Name"],
            "Runner-up Party": x.iloc[1]["Party"],
            "Runner-up Votes": x.iloc[1]["Votes Secured Evm"],
            "Margin": x.iloc[0]["Votes Secured Evm"] - x.iloc[1]["Votes Secured Evm"]
        }))
        .reset_index()
)
result

C:\Users\amanp\AppData\Local\Temp\ipykernel_21588\1758300775.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: pd.Series({

,ParliamentryName,Winner,Winning Party,Winner Votes,Runner-up,Runner-up Party,Runner-up Votes,Margin
0,AJMER,BHAGIRATH CHOUDHARY,BJP,107716,RAMCHANDRA CHOUDHARY,INC,59047,48669
1,ALWAR,BHUPENDER YADAV,BJP,103363,LALIT YADAV,INC,84895,18468
2,AMBALA,VARUN CHAUDHRY,INC,98531,BANTO KATARIA,BJP,86523,12008
3,ANANTNAG-RAJOURI,MIAN ALTAF AHMAD,JKN,53751,MEHBOOBA MUFTI,JKPDP,26483,27268
4,ARAKKONAM,S JAGATHRATCHAKAN,DMK,105052,L VIJAYAN,ADMK,52551,52501
...,...,...,...,...,...,...,...,...
535,Wardha,AMAR SHARADRAO KALE,NCPSP,95035,RAMDAS CHANDRABHAN TADAS,BJP,89968,5067
536,Wayanad,RAHUL GANDHI,INC,112310,ANNIE RAJA,CPI,43626,68684
537,West Delhi,KAMALJEET SEHRAWAT,BJP,153497,MAHABAL MISHRA,AAAP,109365,44132
538,Yavatmal- Washim,SANJAY UTTAMRAO DESHMUKH,SHSUBT,113849,RAJSHRITAI HEMANT PATIL (MAHALLE),SHS,97520,16329
539,Zahirabad,SURESH KUMAR SHETKAR,INC,103129,B. B. PATIL,BJP,85610,17519

In [33]:
ad

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm,Total_Votes,Turnout generalpercent,Votesharepercentage,Votes_pc_party,NOTA_percent,Winning Party,Margin
0,Rajasthan,13,AJMER,1999399,98,KISHANGARH,286257,32885413,1816,BHAGIRATH CHOUDHARY,BJP,107716,1180237,59.029588,9.126642,741151,0.153867,BJP,9245
1,Rajasthan,13,AJMER,1999399,105,KEKRI,264896,32885413,1742,BHAGIRATH CHOUDHARY,BJP,98471,1180237,59.029588,8.343324,741151,0.147597,BJP,9245
2,Rajasthan,13,AJMER,1999399,104,MASUDA,275740,32885413,1436,BHAGIRATH CHOUDHARY,BJP,97421,1180237,59.029588,8.254359,741151,0.121670,BJP,9245
3,Rajasthan,13,AJMER,1999399,99,PUSHKAR,254914,32885413,1496,BHAGIRATH CHOUDHARY,BJP,95780,1180237,59.029588,8.115319,741151,0.126754,BJP,9245
4,Rajasthan,13,AJMER,1999399,102,NASIRABAD,235530,32885413,1225,BHAGIRATH CHOUDHARY,BJP,89146,1180237,59.029588,7.553229,741151,0.103793,BJP,9245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Telangana,5,Zahirabad,1642425,16,Kamareddy,255175,21904129,527,ROMALA BABU DURGAIAH,IPBP,88,1222431,74.428421,0.007199,601,0.043111,INC,17519
61721,Telangana,5,Zahirabad,1642425,35,Narayankhed,237309,21904129,396,ROMALA BABU DURGAIAH,IPBP,80,1222431,74.428421,0.006544,601,0.032394,INC,17519
61722,Telangana,5,Zahirabad,1642425,38,Zaheerabad,275667,21904129,351,ROMALA BABU DURGAIAH,IPBP,74,1222431,74.428421,0.006054,601,0.028713,INC,17519
61723,Telangana,5,Zahirabad,1642425,14,Banswada,197025,21904129,365,ASHOK TALARI,IND,73,1222431,74.428421,0.005972,30999,0.029859,INC,17519
61724,Telangana,5,Zahirabad,1642425,14,Banswada,197025,21904129,365,ROMALA BABU DURGAIAH,IPBP,61,1222431,74.428421,0.004990,601,0.029859,INC,17519

In [34]:
result[margin["ParliamentryName"]=="Araku"]

NameError: name 'margin' is not defined

In [35]:
ad

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm,Total_Votes,Turnout generalpercent,Votesharepercentage,Votes_pc_party,NOTA_percent,Winning Party,Margin
0,Rajasthan,13,AJMER,1999399,98,KISHANGARH,286257,32885413,1816,BHAGIRATH CHOUDHARY,BJP,107716,1180237,59.029588,9.126642,741151,0.153867,BJP,9245
1,Rajasthan,13,AJMER,1999399,105,KEKRI,264896,32885413,1742,BHAGIRATH CHOUDHARY,BJP,98471,1180237,59.029588,8.343324,741151,0.147597,BJP,9245
2,Rajasthan,13,AJMER,1999399,104,MASUDA,275740,32885413,1436,BHAGIRATH CHOUDHARY,BJP,97421,1180237,59.029588,8.254359,741151,0.121670,BJP,9245
3,Rajasthan,13,AJMER,1999399,99,PUSHKAR,254914,32885413,1496,BHAGIRATH CHOUDHARY,BJP,95780,1180237,59.029588,8.115319,741151,0.126754,BJP,9245
4,Rajasthan,13,AJMER,1999399,102,NASIRABAD,235530,32885413,1225,BHAGIRATH CHOUDHARY,BJP,89146,1180237,59.029588,7.553229,741151,0.103793,BJP,9245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Telangana,5,Zahirabad,1642425,16,Kamareddy,255175,21904129,527,ROMALA BABU DURGAIAH,IPBP,88,1222431,74.428421,0.007199,601,0.043111,INC,17519
61721,Telangana,5,Zahirabad,1642425,35,Narayankhed,237309,21904129,396,ROMALA BABU DURGAIAH,IPBP,80,1222431,74.428421,0.006544,601,0.032394,INC,17519
61722,Telangana,5,Zahirabad,1642425,38,Zaheerabad,275667,21904129,351,ROMALA BABU DURGAIAH,IPBP,74,1222431,74.428421,0.006054,601,0.028713,INC,17519
61723,Telangana,5,Zahirabad,1642425,14,Banswada,197025,21904129,365,ASHOK TALARI,IND,73,1222431,74.428421,0.005972,30999,0.029859,INC,17519
61724,Telangana,5,Zahirabad,1642425,14,Banswada,197025,21904129,365,ROMALA BABU DURGAIAH,IPBP,61,1222431,74.428421,0.004990,601,0.029859,INC,17519

In [36]:
pd.read_sql_query("select * from elections",conn)

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm
0,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,APPALANARASA PACHIPENTA,CPI(M),3873
1,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,AVASHYA LAHARI . VARAM,BSP,1155
2,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,KOTHAPALLI GEETHA,BJP,66695
3,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,GUMMA THANUJA RANI,YSRCP,63302
4,Andhra Pradesh,1,Araku,1557153,10,Palakonda,195673,33327256,4441,CHANTI BADNAINA,JBNP,1977
...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,TSERING NAMGYAL,INC,32014
61721,Ladakh,1,Ladakh,190576,1,Leh,92700,134612,338,MOHMAD HANEEFA,IND,5733
61722,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TASHI GYALSON,BJP,10012
61723,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,TSERING NAMGYAL,INC,3756
61724,Ladakh,1,Ladakh,190576,2,Kargil,97876,134612,558,MOHMAD HANEEFA,IND,58710

In [37]:
cursor = conn.cursor()

In [38]:
ad.dtypes

State/Ut Name                  object
Parliamentryconstituencies      int64
ParliamentryName               object
Total Electors In PC            int64
Assemblyconstituencies          int64
AssemblyName                   object
Total Electors In AC            int64
Total Valid Votes In State      int64
Nota Votes Evm In AC            int64
Candidate Name                 object
Party                          object
Votes Secured Evm               int64
Total_Votes                     int64
Turnout generalpercent        float64
Votesharepercentage           float64
Votes_pc_party                  int64
NOTA_percent                  float64
Winning Party                  object
Margin                          int64
dtype: object

In [39]:
cursor.execute("""
    CREATE TABLE final_results (
        "State/Ut Name" VARCHAR(100),
        "Parliamentryconstituencies" INT,
        "ParliamentryName" VARCHAR(100),
        "Total Electors In PC" INT,
        "Assemblyconstituencies" INT,
        "AssemblyName" VARCHAR(100),
        "Total Electors In AC" INT,
        "Total Valid Votes In State" INT,
        "Nota Votes Evm In AC" INT,
        "Candidate Name" VARCHAR(100),
        "Party" VARCHAR(100),
        "Votes Secured Evm" INT,
        "Total_Votes" INT,
        "Turnout generalpercent" DECIMAL(15,2),
        "Votesharepercentage" DECIMAL(15,2),
        "Votes_pc_party" INT,
        "Winning Party" VARCHAR(100),
        "Margin" INT
    );
""")

OperationalError: table final_results already exists

In [40]:
final_results = ad.to_sql("final_results", conn, if_exists="replace", index=False)

In [41]:
final_results

61725

In [42]:
conn

In [43]:
pd.read_sql_query("select * from final_results",conn)

,State/Ut Name,Parliamentryconstituencies,ParliamentryName,Total Electors In PC,Assemblyconstituencies,AssemblyName,Total Electors In AC,Total Valid Votes In State,Nota Votes Evm In AC,Candidate Name,Party,Votes Secured Evm,Total_Votes,Turnout generalpercent,Votesharepercentage,Votes_pc_party,NOTA_percent,Winning Party,Margin
0,Rajasthan,13,AJMER,1999399,98,KISHANGARH,286257,32885413,1816,BHAGIRATH CHOUDHARY,BJP,107716,1180237,59.029588,9.126642,741151,0.153867,BJP,9245
1,Rajasthan,13,AJMER,1999399,105,KEKRI,264896,32885413,1742,BHAGIRATH CHOUDHARY,BJP,98471,1180237,59.029588,8.343324,741151,0.147597,BJP,9245
2,Rajasthan,13,AJMER,1999399,104,MASUDA,275740,32885413,1436,BHAGIRATH CHOUDHARY,BJP,97421,1180237,59.029588,8.254359,741151,0.121670,BJP,9245
3,Rajasthan,13,AJMER,1999399,99,PUSHKAR,254914,32885413,1496,BHAGIRATH CHOUDHARY,BJP,95780,1180237,59.029588,8.115319,741151,0.126754,BJP,9245
4,Rajasthan,13,AJMER,1999399,102,NASIRABAD,235530,32885413,1225,BHAGIRATH CHOUDHARY,BJP,89146,1180237,59.029588,7.553229,741151,0.103793,BJP,9245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61720,Telangana,5,Zahirabad,1642425,16,Kamareddy,255175,21904129,527,ROMALA BABU DURGAIAH,IPBP,88,1222431,74.428421,0.007199,601,0.043111,INC,17519
61721,Telangana,5,Zahirabad,1642425,35,Narayankhed,237309,21904129,396,ROMALA BABU DURGAIAH,IPBP,80,1222431,74.428421,0.006544,601,0.032394,INC,17519
61722,Telangana,5,Zahirabad,1642425,38,Zaheerabad,275667,21904129,351,ROMALA BABU DURGAIAH,IPBP,74,1222431,74.428421,0.006054,601,0.028713,INC,17519
61723,Telangana,5,Zahirabad,1642425,14,Banswada,197025,21904129,365,ASHOK TALARI,IND,73,1222431,74.428421,0.005972,30999,0.029859,INC,17519
61724,Telangana,5,Zahirabad,1642425,14,Banswada,197025,21904129,365,ROMALA BABU DURGAIAH,IPBP,61,1222431,74.428421,0.004990,601,0.029859,INC,17519